#!/usr/bin/env python3
"""Generate the Shadow Software repo banner family.

One template, four products. The skeleton — dark radial ground, faint hex lattice,
the hooded-hexagon mark, a product motif, then wordmark / subtitle / strapline /
rule / byline — is fixed. Only the ACCENT and the MOTIF change.

It is drawn as SVG and rasterised with rsvg-convert, not generated by an image
model: the whole design is type and vector, and a diffusion model cannot set type.
"""
import subprocess
import sys
from pathlib import Path

OUT = Path(__file__).parent

# The hooded-hexagon mark, from assets/img/shadow-mark.svg. Identical everywhere —
# it is the one element that must not vary, because it is the company's signature.
MARK = """
  <g transform="translate(120 130) scale(5.6)">
    <path d="M20 1.5 37 11.25v19.5L20 40.5 3 30.75v-19.5z" fill="{accent}" opacity="0.22" filter="url(#soft)"/>
    <path d="M20 1.5 37 11.25v19.5L20 40.5 3 30.75v-19.5z" fill="#0d0d0d" stroke="{accent}" stroke-width="2" stroke-linejoin="round"/>
    <path d="M20 11c-4.4 0-7.8 3.3-7.8 8 0 2.6 1.1 4.7 2.6 6.2-1.7 1.1-2.9 2.7-3.3 4.8h17c-.4-2.1-1.6-3.7-3.3-4.8 1.5-1.5 2.6-3.6 2.6-6.2 0-4.7-3.4-8-7.8-8z" fill="#ededed"/>
    <ellipse cx="20" cy="19.5" rx="3.6" ry="4.2" fill="#0d0d0d"/>
  </g>
"""

# --- product motifs -------------------------------------------------------
# Each sits at translate(480 250), the same optical slot the ETH coin occupies in
# the original, so the four banners align when you flick between them.

MOTIF_CRYPTO = """
  <g transform="translate(480 250)">
    <ellipse cx="0" cy="118" rx="70" ry="14" fill="#000" opacity="0.35"/>
    <circle r="92" fill="url(#face)" stroke="{deep}" stroke-width="4"/>
    <circle r="78" fill="none" stroke="#0d0d0d" stroke-opacity="0.16" stroke-width="3"/>
    <g fill="#0d0d0d">
      <path d="M0 -50 -27 4 0 18 27 4z" opacity="0.92"/>
      <path d="M0 26 -27 10 0 54 27 10z" opacity="0.78"/>
    </g>
  </g>
"""

# AGT: a rifle-scope reticle. Reads instantly as firearms without drawing a gun.
MOTIF_AGT = """
  <g transform="translate(480 250)">
    <ellipse cx="0" cy="118" rx="70" ry="14" fill="#000" opacity="0.35"/>
    <circle r="92" fill="url(#face)" stroke="{deep}" stroke-width="4"/>
    <circle r="78" fill="#0d0d0d" fill-opacity="0.82" stroke="#0d0d0d" stroke-opacity="0.2" stroke-width="2"/>
    <g stroke="{accent}" stroke-width="5" stroke-linecap="round">
      <path d="M0 -72 V-26 M0 26 V72 M-72 0 H-26 M26 0 H72"/>
      <path d="M0 -14 V14 M-14 0 H14" stroke-width="3" stroke-opacity="0.55"/>
    </g>
    <circle r="4.5" fill="{accent}"/>
    <g stroke="{accent}" stroke-opacity="0.35" stroke-width="2" fill="none">
      <circle r="46"/>
    </g>
  </g>
"""

# Broadside: a folded broadsheet — the folio rule and two columns of type.
MOTIF_BROADSIDE = """
  <g transform="translate(480 250)">
    <ellipse cx="0" cy="118" rx="70" ry="14" fill="#000" opacity="0.35"/>
    <g transform="translate(-72 -96)">
      <rect width="144" height="196" rx="4" fill="#f4efe4"/>
      <rect width="144" height="196" rx="4" fill="none" stroke="{deep}" stroke-width="3"/>
      <!-- nameplate -->
      <rect x="14" y="16" width="116" height="15" rx="2" fill="#1c1a17"/>
      <!-- folio rule -->
      <rect x="14" y="38" width="116" height="2.5" fill="{accent}"/>
      <!-- two columns of type -->
      <g fill="#1c1a17" opacity="0.42">
        <rect x="14" y="50" width="52" height="3.6"/><rect x="14" y="59" width="52" height="3.6"/>
        <rect x="14" y="68" width="52" height="3.6"/><rect x="14" y="77" width="52" height="3.6"/>
        <rect x="14" y="86" width="38" height="3.6"/>
        <rect x="78" y="50" width="52" height="3.6"/><rect x="78" y="59" width="52" height="3.6"/>
        <rect x="78" y="68" width="52" height="3.6"/><rect x="78" y="77" width="52" height="3.6"/>
        <rect x="78" y="86" width="44" height="3.6"/>
      </g>
      <!-- a plate -->
      <rect x="14" y="100" width="116" height="42" rx="2" fill="{accent}" opacity="0.28"/>
      <g fill="#1c1a17" opacity="0.42">
        <rect x="14" y="152" width="116" height="3.6"/><rect x="14" y="161" width="116" height="3.6"/>
        <rect x="14" y="170" width="84" height="3.6"/>
      </g>
    </g>
  </g>
"""

# Blocks: the editorial furniture — stacked block cards, one highlighted.
MOTIF_BLOCKS = """
  <g transform="translate(480 250)">
    <ellipse cx="0" cy="118" rx="70" ry="14" fill="#000" opacity="0.35"/>
    <g transform="translate(-78 -92)">
      <rect x="0" y="0" width="156" height="44" rx="5" fill="#f4efe4" stroke="{deep}" stroke-width="3"/>
      <rect x="12" y="12" width="30" height="5" rx="2.5" fill="{accent}"/>
      <rect x="12" y="24" width="118" height="4" rx="2" fill="#1c1a17" opacity="0.38"/>
      <rect x="12" y="33" width="90" height="4" rx="2" fill="#1c1a17" opacity="0.38"/>

      <rect x="0" y="56" width="156" height="44" rx="5" fill="{accent}" fill-opacity="0.16" stroke="{accent}" stroke-width="3"/>
      <rect x="12" y="68" width="40" height="5" rx="2.5" fill="{accent}"/>
      <rect x="12" y="80" width="118" height="4" rx="2" fill="#f4efe4" opacity="0.62"/>
      <rect x="12" y="89" width="72" height="4" rx="2" fill="#f4efe4" opacity="0.62"/>

      <rect x="0" y="112" width="156" height="44" rx="5" fill="#f4efe4" stroke="{deep}" stroke-width="3"/>
      <rect x="12" y="124" width="34" height="5" rx="2.5" fill="{accent}"/>
      <rect x="12" y="136" width="118" height="4" rx="2" fill="#1c1a17" opacity="0.38"/>
      <rect x="12" y="145" width="100" height="4" rx="2" fill="#1c1a17" opacity="0.38"/>
    </g>
  </g>
"""

TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" width="1544" height="500" viewBox="0 0 1544 500" role="img" aria-label="{alt}">
  <defs>
    <radialGradient id="bg" cx="16%" cy="0%" r="120%">
      <stop offset="0%" stop-color="{glow}"/>
      <stop offset="45%" stop-color="#0b0b0b"/>
      <stop offset="100%" stop-color="#060606"/>
    </radialGradient>
    <linearGradient id="face" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="{light}"/>
      <stop offset="52%" stop-color="{accent}"/>
      <stop offset="100%" stop-color="{deep}"/>
    </linearGradient>
    <filter id="soft" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="14"/>
    </filter>
  </defs>

  <rect width="1544" height="500" fill="url(#bg)"/>

  <g stroke="{accent}" stroke-opacity="0.06" fill="none" stroke-width="3.5">
    <path d="M230 90 290 125v70l-60 35-60-35v-70z"/>
    <path d="M1330 320 1390 355v70l-60 35-60-35v-70z"/>
    <path d="M1230 70 1272 94v48l-42 24-42-24V94z"/>
  </g>
{mark}{motif}
  <g font-family="-apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif">
    <text x="640" y="228" font-size="{h1size}" font-weight="800" letter-spacing="-2" fill="#ffffff">{headline}</text>
    <text x="644" y="292" font-size="44" font-weight="600" letter-spacing="1" fill="#c9c9c9">{sub}</text>
    <text x="644" y="352" font-size="{tagsize}" font-weight="500" letter-spacing="0.5" fill="#7f7f7f">{tag}</text>
    <rect x="644" y="378" width="360" height="5" rx="2.5" fill="{accent}"/>
    <text x="1024" y="382" font-size="20" font-weight="600" letter-spacing="0.5" fill="{deep}">by Shadow Software</text>
  </g>
</svg>
"""

PRODUCTS = {
    # The crypto banner is REPRODUCED, not redesigned — it is the one already
    # shipped to wordpress.org, and the family is being built to match it.
    "crypto-for-woocommerce": dict(
        accent="#8fd468", light="#c2f394", deep="#5aa63c", glow="#12351c",
        motif=MOTIF_CRYPTO,
        h1a="Accept", h1b="Crypto", h1size=86,
        sub="for WooCommerce",
        tag="ETH · USDC · USDT · Bitcoin — self-custodial, on-chain verified", tagsize=27,
        alt="Accept Crypto for WooCommerce — by Shadow Software",
    ),
    # Amber/brass: firearms, without being lurid about it.
    "agt-for-woocommerce": dict(
        accent="#d9a441", light="#f2cf85", deep="#9a6f22", glow="#3a2a0e",
        motif=MOTIF_AGT,
        h1a="Sync", h1b="Your Listings", h1size=80,
        sub="for WooCommerce",
        tag="American Gun Trader — inventory, pricing and availability, in step", tagsize=25,
        alt="Sync Your Listings for WooCommerce — American Gun Trader — by Shadow Software",
    ),
    # Oxblood: the newspaper's own accent.
    "broadside-theme-for-wordpress": dict(
        accent="#b34747", light="#e39191", deep="#7d2323", glow="#3a1414",
        motif=MOTIF_BROADSIDE,
        h1a="The", h1b="Broadside", h1size=86,
        sub="a broadsheet theme for WordPress",
        tag="Blackletter masthead · folio rule · three-column lead grid", tagsize=27,
        alt="Broadside — a broadsheet theme for WordPress — by Shadow Software",
    ),
    "broadside-blocks-for-wordpress": dict(
        accent="#b34747", light="#e39191", deep="#7d2323", glow="#3a1414",
        motif=MOTIF_BLOCKS,
        h1a="Broadside", h1b="Blocks", h1size=80,
        sub="editorial furniture for WordPress",
        tag="Short answer · takeaways · contents · FAQ schema · sources", tagsize=26,
        alt="Broadside Blocks — editorial furniture for WordPress — by Shadow Software",
    ),
}


def main() -> None:
    for name, p in PRODUCTS.items():
        fields = {k: v for k, v in p.items() if k != "motif"}

        # Build the headline as markup, so a one-word product ("Broadside") does not
        # leave an empty <tspan> and a trailing space behind it.
        if p["h1b"]:
            fields["headline"] = (
                f'{p["h1a"]} <tspan fill="{p["accent"]}">{p["h1b"]}</tspan>'
            )
        else:
            fields["headline"] = p["h1a"]

        svg = TEMPLATE.format(
            mark=MARK.format(**fields),
            motif=p["motif"].format(**fields),
            **fields,
        )
        svg_path = OUT / f"{name}.svg"
        png_path = OUT / f"{name}.png"
        svg_path.write_text(svg)
        subprocess.run(
            ["rsvg-convert", "-w", "1544", "-h", "500", str(svg_path), "-o", str(png_path)],
            check=True,
        )
        kb = png_path.stat().st_size // 1024
        print(f"  {name}.png  {kb} KB")


if __name__ == "__main__":
    main()
